---
name: "Release"

on:
  push:
    tags:
      - "*"

env:
  # NOTE: the IMAGE_PATH variable needs to be set as an environment variable on each
  #       repository for this variable to be properly set, otherwise it will be blank.
  IMAGE: "${{ vars.ORG_IMAGE_REGISTRY_HOSTNAME }}/${{ vars.IMAGE_PATH }}"

jobs:
  Release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.22"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
        
      - name: "Login to Image Registry"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ vars.ORG_IMAGE_REGISTRY_HOSTNAME}}"
          username: "${{ secrets.ORG_IMAGE_REGISTRY_USERNAME }}"
          password: "${{ secrets.ORG_IMAGE_REGISTRY_PASSWORD }}"
      
      - name: "Build and Push"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ env.IMAGE }}:${{ github.ref_name }},${{ env.IMAGE }}:latest"

      - name: "Run Go Releaser"
        uses: "goreleaser/goreleaser-action@v3"
        with:
          version: "latest"
          args: "release --clean -f ./.goreleaser.yml"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

          # TODO: add homebrew tap
          # HOMEBREW_TAP_GITHUB_TOKEN: "${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}"

      - name: "Generate Controller Manifests"
        run: |
          make kustomize
          cd config/manager && ../../bin/kustomize edit set image controller=${{ env.IMAGE }}:${{ github.ref_name }}
          cd ../../ && bin/kustomize build config/default > /tmp/manifests.yaml

      - name: "Upload Controller Manifests to Release"
        uses: "xresloader/upload-to-github-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "/tmp/manifests.yaml"
          tags: true
          verbose: true
          update_latest_release: true
